### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by maximecolin** [Elao/elao_#3]
Layout : `sitemap.xml.twig`

Configurer les valeurs par défaut dans `config.yml` :

```yaml
defaultpages:
  sitemap:
    changefreq: daily
    priority: 1
```

Possibilité de redéfinir ces valeurs dans le frontmatter des pages :

```markdown
---
sitemap: { changefreq: daily, priority: 1 }
--- 
```
